name: Helm Chart Validation

on:
  push:
    paths:
      - 'charts/**'
  pull_request:
    paths:
      - 'charts/**'

jobs:
  helm-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Run helm lint
        run: |
          helm lint charts/keycloak

      - name: Dry-run rendering
        run: |
          helm template keycloak charts/keycloak --dry-run --debug
