replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
