name: Deploy to Dev/Staging/Prod

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Setup Kubernetes Cluster (kind for dev/staging or real for prod)
        run: |
          if [[ "${{ github.event.inputs.environment }}" != "prod" ]]; then
            echo "Using kind cluster for dev/staging"
            curl -Lo kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
            chmod +x kind
            sudo mv kind /usr/local/bin/
            kind create cluster --wait 60s
            kubectl cluster-info
          else
            echo "For prod, please configure kubeconfig via secrets"
          fi

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install keycloak charts/keycloak --set ingress.enabled=false --set service.port=8080

      - name: Cleanup kind cluster (if dev/staging)
        if: ${{ github.event.inputs.environment != 'prod' }}
        run: kind delete cluster
