name: Helm Test on K3s

on:
  push:
    paths:
      - 'charts/**'
  pull_request:
    paths:
      - 'charts/**'

jobs:
  helm-k3s-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install k3s
        run: |
          curl -sfL https://get.k3s.io | sh -
          sudo cp /etc/rancher/k3s/k3s.yaml kubeconfig
          sudo chown $USER:$USER kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Helm lint
        run: helm lint charts/keycloak

      - name: Helm install Keycloak
        run: helm install keycloak charts/keycloak --set ingress.enabled=false --set service.port=8080

      - name: Wait for Keycloak pod
        run: kubectl wait --for=condition=Ready pod -l app=keycloak --timeout=120s

      - name: Run helm test
        run: helm test keycloak

      - name: Cleanup Helm release
        run: helm uninstall keycloak
